### ISSUE TITLE
Loading map is taking forever

### ISSUE THREAD

**Issue by flaiming** [jsmesami/naovoce#7]
Call for https://na-ovoce.cz/api/v1/fruit/ is taking really long and it's a lot of data. It should probably load only essential data for map markers and load data for specific map marked on demand (upon click on marker). And/or map should load only visible markers.

**Comment by jsmesami** [comment]
Yes, this is indeed an issue with slow connectivity, and will grow unbearable with more markers in the map. But consider this: If we only loaded markers for specific frame, we should also be able to load the remaining markers when user shifts/zooms out the viewport. The viewport can also be zoomed-out to show whole europe, which shows essentialy _all_ the markers. So this would be significantly hard to implement with little or zero impact. 

Ideas for possible improvement:
- server-side clustering
- streaming response + lazy map update
- only load changes since last time, saving data locally (I am working on this right now)

**Comment by flaiming** [comment]
jsmesami: I was working at current sreality.cz portal, which is solving this problem by server side clustering for current user viewport. That's in my opinion best optimized solution, but also hardest to implement. I'll look into possible out-of-the-box solutions.

**Comment by flaiming** [comment]
https://github.com/biodiv/anycluster looks promissiong, but I probably start with something easier, like #2.

**Comment by jsmesami** [comment]
The anycluster demo looks great! I had some success with [this branch](https://github.com/jsmesami/naovoce/tree/save-loaded-markers-locally), but it's a lot of frontend work based on unstable browser features. Whatsmore, we have PostGIS to do the heavy lifting.

**Comment by jsmesami** [comment]
Since I abandoned [this branch](https://github.com/jsmesami/naovoce/tree/save-loaded-markers-locally) for reasons described above, I'm closing this in favour of #28 and #29.
